{% set name = "redisgraph" %}
{% set version = "2.4.4" %}


package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redisgraph-{{ version }}.tar.gz
  sha256: bcc1d52d77e932a16ab1b43f907845dfe8acf5fdffc671b9cc94bb53e3c7c9fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
    - tox
    - hiredis
  run:
    - prettytable
    - python >=3.6
    - redis-py
    - poetry
    - tox
    - hiredis

test:
  imports:
    - redisgraph
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RedisGraph/redisgraph-py
  summary: RedisGraph Python Client
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Luxxii
