{% set name = "redisgraph" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redisgraph-{{ version }}.tar.gz
  sha256: 2f82633f99e832461e5f156cfb7d8e1ff3f2df8b1962b93b1a1051b538a09b90

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
    - tox
  run:
    - prettytable
    - python >=3.6
    - redis-py
    - poetry
    - tox

test:
  imports:
    - redisgraph
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RedisGraph/redisgraph-py
  summary: RedisGraph Python Client
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Luxxii
