{% set name = "redisgraph" %}
{% set version = "2.4.1" %}


package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redisgraph-{{ version }}.tar.gz
  sha256: b67de1456ca19be06aee1430e07d8e070b85688d1e729406d6c24f13ce1e8e94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
    - tox
    - hiredis
  run:
    - prettytable
    - python >=3.6
    - redis-py
    - poetry
    - tox
    - hiredis

test:
  imports:
    - redisgraph
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RedisGraph/redisgraph-py
  summary: RedisGraph Python Client
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Luxxii
